### ISSUE TITLE
Accessors

### ISSUE THREAD

**Issue by PovilasKorop** [ryk4/bookstore#10]
https://github.com/ryk4/bookstore/blob/4197539aec2b0ff01649e3fe9404273da08f24fd/app/Models/Book.php#L55

Matau darai custom metodus modelyje, gal pravartu paskaityti apie Accessors ir Mutators
https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor

**Comment by ryk4** [comment]
Suprantu kam ir kada naudojami Accessors ir Mutators. Nelabai suprantu kaip galeciau pritaikyti juos siame scenarijuje. isAddedThisWeek jug nera tiesiog created_at data. Naudojant Accessor su created_at, reikstu kad everytime created_at is returned from db, subtract 7 days, but then the value would not be correct. This method isAddedThisWeek() is used purely by the blade view to determine if the book is "new" or not. 

Gal as netaip supratau jusu komentara ?

**Comment by PovilasKorop** [comment]
@ryk4 komentaras buvo ne apie šitą metodą konkrečiai, bet bendrai matau kad daug custom metodų, gal kai kuriems iš jų apsimoka naudoti Accessors. Tavo nuožiūra.
