### ISSUE TITLE
Galimai neteisinga where sąlyga

### ISSUE THREAD

**Issue by PovilasKorop** [ryk4/bookstore#3]
https://github.com/ryk4/bookstore/blob/4197539aec2b0ff01649e3fe9404273da08f24fd/app/Http/Controllers/BookController.php#L32

Netestavau bet turiu tokį įtarimą kad paieška pagal title nesuveiks, arba pagal kažkurią iš tų trijų sąlygų.
Nes gaunasi neteisingas SQL: `where status... AND authors... OR title`
O turėtų būti `where status AND (authors OR title)`

Straipsnis apie tai: https://laraveldaily.com/and-or-and-brackets-with-eloquent/

**Comment by ryk4** [comment]
fixed.
