### ISSUE TITLE
Nereikia Response::view

### ISSUE THREAD

**Issue by PovilasKorop** [ryk4/bookstore#4]
https://github.com/ryk4/bookstore/blob/4197539aec2b0ff01649e3fe9404273da08f24fd/app/Http/Controllers/BookController.php#L37

Užtenka tiesiog `return view()` kaip ir kitur.

**Comment by ryk4** [comment]
i think Response needs to be there, because i am returning a cookie along with it? tested with return view() and cookie did not seem to work. will look further  into it.

**Comment by PovilasKorop** [comment]
@ryk4 you're right, sorry, didn't look too closely on the cookie.
