### ISSUE TITLE
Request->validated()

### ISSUE THREAD

**Issue by PovilasKorop** [ryk4/bookstore#7]
https://github.com/ryk4/bookstore/blob/4197539aec2b0ff01649e3fe9404273da08f24fd/app/Http/Controllers/BookController.php#L110

Vietoje priskyrimo visų laukų ir `save()` galima tiesiog `$book->update($request->validated());`

Čia su sąlygą kad naudoji `$fillable` ir Form Request klasę, matau abu naudoji šiuo atveju.

**Comment by ryk4** [comment]
Book update fixed. need to look at the others

**Comment by ryk4** [comment]
Done.
