### ISSUE TITLE
BelongsToMany not DB::table

### ISSUE THREAD

**Issue by PovilasKorop** [ryk4/bookstore#8]
https://github.com/ryk4/bookstore/blob/4197539aec2b0ff01649e3fe9404273da08f24fd/app/Http/Controllers/BookController.php#L119

Čia visur Controlleryje kur yra operacijos `DB::table(...)` turi būti naudojami many-to-many relationships metodai attach/detach/sync, pvz `$book->authors()->detach($author_id)`;

Paskaityk: https://laravel.com/docs/8.x/eloquent-relationships#attaching-detaching
Pažiūrėk: https://www.youtube.com/watch?v=V5xINbA-z9o

**Comment by ryk4** [comment]
fixed. not closing this as will need to read up more about attaching/detaching and Eloquent itself.
