### ISSUE TITLE
Nereikia auth::user()

### ISSUE THREAD

**Issue by PovilasKorop** [ryk4/bookstore#9]
https://github.com/ryk4/bookstore/blob/4197539aec2b0ff01649e3fe9404273da08f24fd/app/Http/Controllers/UserController.php#L23

Nereikia perdavinėti iš čia, nes Blade tu gali pasiekti bet kokį lauką su `auth()->user()`, pvz `auth()->user()->name` ar `auth()->user()->email`

**Comment by ryk4** [comment]
done.
